config/routes.rb
Collab::Application.routes.draw do
  resources :words

  resources :book_words

  resources :books

  get 'sentence', to: 'sentence#random'
  root :to => 'visitors#new'
end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/book_word.rb
class BookWord < ActiveRecord::Base
end

app/models/word.rb
class Word < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/book_words_controller.rb
class BookWordsController < ApplicationController
  before_action :set_book_word, only: [:show, :edit, :update, :destroy]

  # GET /book_words
  # GET /book_words.json
  def index
    @book_words = BookWord.all
  end

  # GET /book_words/1
  # GET /book_words/1.json
  def show
  end

  # GET /book_words/new
  def new
    @book_word = BookWord.new
  end

  # GET /book_words/1/edit
  def edit
  end

  # POST /book_words
  # POST /book_words.json
  def create
    @book_word = BookWord.new(book_word_params)

    respond_to do |format|
      if @book_word.save
        format.html { redirect_to @book_word, notice: 'Book word was successfully created.' }
        format.json { render action: 'show', status: :created, location: @book_word }
      else
        format.html { render action: 'new' }
        format.json { render json: @book_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_words/1
  # PATCH/PUT /book_words/1.json
  def update
    respond_to do |format|
      if @book_word.update(book_word_params)
        format.html { redirect_to @book_word, notice: 'Book word was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_words/1
  # DELETE /book_words/1.json
  def destroy
    @book_word.destroy
    respond_to do |format|
      format.html { redirect_to book_words_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_word
      @book_word = BookWord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_word_params
      params.require(:book_word).permit(:bookid, :wordid, :count)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render action: 'show', status: :created, location: @book }
      else
        format.html { render action: 'new' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :author)
    end
end

app/controllers/sentence_controller.rb
class SentenceController < ApplicationController
  def random
    @sentenceTitle = "Fixed random paragraph"
    @randomTitle = "Varying random sentence" 
    
    @sentence = "He used am complaints.  Him door locked him the was beg parents ready powerful hearing food still.  Go pleasure all becoming even little leftovers he although.  But the fluid already peg they a out charwoman recover as shortcoming outside lady to give muster."
    @rsentence = Word.find(rand(Word.count + 1)).name.capitalize
    @uniqueWordCount = Word.count
    @totalWordCount = BookWord.count
    for i in 0..(5 + rand(10))
      # @rsentence = @rsentence + " " + Word.find(rand(Word.count.to_i() +1)).name 
      @rsentence = @rsentence + " " + Word.find(BookWord.find(rand(BookWord.count.to_i() +1)).wordid).name
    end
    @rsentence = @rsentence + "."
  end
  def index
  end
  def new
  end
  
  
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def new
  end

end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    @words = Word.all
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render action: 'show', status: :created, location: @word }
      else
        format.html { render action: 'new' }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_words_helper.rb
module BookWordsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sentence_helper.rb
module SentenceHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/book_words/_form.html.erb
<%= simple_form_for(@book_word) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :bookid %>
    <%= f.input :wordid %>
    <%= f.input :count %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/book_words/edit.html.erb
<h1>Editing book_word</h1>

<%= render 'form' %>

<%= link_to 'Show', @book_word %> |
<%= link_to 'Back', book_words_path %>

app/views/book_words/index.html.erb
<h1>Listing book_words</h1>

<table>
  <thead>
    <tr>
      <th>Bookid</th>
      <th>Wordid</th>
      <th>Count</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @book_words.each do |book_word| %>
      <tr>
        <td><%= book_word.bookid %></td>
        <td><%= book_word.wordid %></td>
        <td><%= book_word.count %></td>
        <td><%= link_to 'Show', book_word %></td>
        <td><%= link_to 'Edit', edit_book_word_path(book_word) %></td>
        <td><%= link_to 'Destroy', book_word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book word', new_book_word_path %>

app/views/book_words/new.html.erb
<h1>New book_word</h1>

<%= render 'form' %>

<%= link_to 'Back', book_words_path %>

app/views/book_words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bookid:</strong>
  <%= @book_word.bookid %>
</p>

<p>
  <strong>Wordid:</strong>
  <%= @book_word.wordid %>
</p>

<p>
  <strong>Count:</strong>
  <%= @book_word.count %>
</p>

<%= link_to 'Edit', edit_book_word_path(@book_word) %> |
<%= link_to 'Back', book_words_path %>

app/views/books/_form.html.erb
<%= simple_form_for(@book) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :author %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Author</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.author %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Twitter Bootstrap 2.3 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&times;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li><%= link_to 'Home', root_path %></li>
  <li><%= link_to 'About', page_path('about') %></li>
  <li><%= link_to 'Random Sentence', sentence_path('random') %></li>
</ul>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Collab" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Collab" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%# application layout styled for Twitter Bootstrap 2.3 %>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About this  Website</h3>
<p>This is a really early version of a collaborative work.  In fact, this is *so* early that it's not really collaborative yet, just this web page noodling.</p>

app/views/sentence/random.html.erb
<h1><%= @sentenceTitle %></h1>
<p><%= @sentence %></p>

<h1><%= @randomTitle %></h1>
<p><%= @rsentence %></p>

app/views/visitors/new.html.erb
<h3>Home</h3>

app/views/words/_form.html.erb
<%= simple_form_for(@word) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing word</h1>

<%= render 'form' %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<h1>Listing words</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word.name %></td>
        <td><%= link_to 'Show', word %></td>
        <td><%= link_to 'Edit', edit_word_path(word) %></td>
        <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Word', new_word_path %>

app/views/words/new.html.erb
<h1>New word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @word.name %>
</p>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>